version: '3.8'
services:
  postgres:
    image: 'postgres:15-alpine'
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: 'dbpos'
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'admin123'
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
